### ISSUE TITLE
Typings don't work with VSCode

### ISSUE THREAD

**Issue by linearaccelerator** [Hypixel-API-Reborn/hypixel-api-reborn#17]
When I use a property (like Player.nickname) in my project, it shows up as "any" type, despite typings having it as "string" type
![Player.nickname screenshot](https://user-images.githubusercontent.com/64271566/92594325-e80cd400-f2a2-11ea-9316-0a321b1c5792.png)
![Typings file screenshot](https://user-images.githubusercontent.com/64271566/92594536-328e5080-f2a3-11ea-9aa6-f399490398d3.png)

**Comment by StavZ** [comment]
So weird. Works fine for me. (Tested on js and ts)

**Comment by StavZ** [comment]
Make sure you are using the latest version

**Comment by linearaccelerator** [comment]
I updated to newest VSCode version, but the typings still don't show up

**Comment by StavZ** [comment]
> Make sure you are using the latest version
I meant the latest version of hypixel-api-reborn
