### ISSUE TITLE
[SUGGESTION] Change code to not throw error when player requested does not exist

### ISSUE THREAD

**Issue by skyeredwood** [Hypixel-API-Reborn/hypixel-api-reborn#206]
I'm trying to make an application using Hypixel-API-Reborn (it's great by the way thank you so much for doing this), but every time a non-existent player is requested using, say, Client.getPlayer(), the Errors.PLAYER_DOES_NOT_EXIST error is thrown. If it just returned no value then a developer could check using a callback function whether the function returned a value then return an error in their app instead of the entire app crashing. This would be incredibly helpful.

**Comment by ChiefChippy2** [comment]
you can use
```js
const {Errors} = require('hypixel-api-reborn')
Client.getPlayer(...).then(player=>{...do whatever}).catch(e=>{
if(e==Errors.PLAYER_DOES_NOT_EXIST) return /* code for when player doesn't exist */
})
// or with await
const player = await Client.getPlayer(...).catch(e=>{...handle error here});
// kim code wont stop executing here so
// or 
try{
  const p = await Client.getPlayer(...);
etc etc
} catch (e){
  // handle error
}
```
The issue is if we return undefined for this method, it doesn't give much insight on what happened : did the api die? was the ign incorrect? internal code error? no internet connection?

**Comment by skyeredwood** [comment]
Ah of course. I was being an idiot and forgetting the try-catch method. Thanks :)
