### ISSUE TITLE
Inconsistency with timestamp names in SkyblockMember

### ISSUE THREAD

**Issue by Antonio32A** [Hypixel-API-Reborn/hypixel-api-reborn#275]
Timestamp based names aren't consistent, we have:
- `firstJoinTimestamp`, `firstJoinAt`
- `firstJoinHubTimestamp`, `firstJoinHubAt`
- `lastSave` (no timestamp), `lastSaveAt`
- `lastDeathAt`, `lastDeath` (no timestamp, opposite order)

**Comment by porterporter** [comment]
got it, i'll double check and PR in a bit
