### ISSUE TITLE
getPlayer will fail and thorw an error if user has never played woolwars

### ISSUE THREAD

**Issue by Kathund** [Hypixel-API-Reborn/hypixel-api-reborn#432]
### Bug report

- Part of code where error occurred
Woolwars getting class
- What error occurred
TypeError: Cannot read properties of undefined (reading 'selected_class')
When running getPlayer it will fail if the user has never played woolwars because it cant get there stats. I found this error using stavzdev as a test username/uuid

**Comment by ChiefChippy2** [comment]
Probably lacking a ?. here
https://github.com/Hypixel-API-Reborn/hypixel-api-reborn/blob/master/src/structures/MiniGames/WoolWars.js#L41

**Comment by Zickles** [comment]
will make a pr for it
(cuz kath asked me to)
![image](https://github.com/Hypixel-API-Reborn/hypixel-api-reborn/assets/76439587/94ca2a37-0371-44d0-8fed-10a1ac3243ee)
